### ISSUE TITLE
Add node affinity

### ISSUE THREAD

**Issue by bartlettc22** [ReadyTalk/vault-helm-chart#6]
Ensure that consul and vault pods are spaced out amongst all the kubernetes nodes to ensure failure in one AZ doesn't disrupt service

**Comment by avoidik** [comment]
Actually it is easier than expected.

Consul statefulset
```
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - consul
              topologyKey: "kubernetes.io/hostname"
```

Vault deployment
```
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - vault
            topologyKey: "kubernetes.io/hostname"
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - consul
            topologyKey: "kubernetes.io/hostname"
```

This gives evenly distributed Consul/Vault pods, where every single Consul entity will have one Vault entity.

Any feedback appreciated
